docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'laminas-i18n-phone-number'
site_description: ''
repo_url: 'https://github.com/laminas/laminas-i18n-phone-number'
extra:
    project: Components
    installation:
        config_provider_class: 'Laminas\i18n-phone-number\ConfigProvider'
        module_class: 'Laminas\i18n-phone-number\Module'
